### ISSUE TITLE
Deakin OBTP

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/release#107]
Add one touch to join function to Deakin Meeting Room UI with Cisco VC

[https://app.zenhub.com/files/278007102/e6485fd4-ceef-4175-81f4-61b489535f56/download](https://app.zenhub.com/files/278007102/e6485fd4-ceef-4175-81f4-61b489535f56/download)

**Comment by caspiano** [comment]
Tracking issue for complete feature.
