### ISSUE TITLE
Rename `frontends` to `frontend-loader`

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/release#118]
The word `frontends` is overloaded at the moment, causing confusion.

**Describe the solution you'd like**

Rename the `frontends` service to `frontend-loader`

**Additional context**

https://github.com/PlaceOS/frontends/pull/31

**Comment by caspiano** [comment]
Let's target `1.2109.0` for this change.

**Comment by caspiano** [comment]
@viv-4 @OllieMoylette 

We'll keep `frontends` as a tag for 1 to 2 versions.

@kimburgess could we create the `frontend-loader` image from the next patch to this release as well as `frontends`?

**Comment by kimburgess** [comment]
Is there a strong argument for that parallel naming? This doesn't avoid a breaking change, just changes when it happens. 

Rolling image tags are not currently available so any infra updates will need to change a tag reference with the move to a new version. I'm not aware of any docker registry support for flagging a deprecation / providing any warn on use either. We can definitely push as multiple tags, but may be simpler to just avoid this altogether.

**Comment by viv-4** [comment]
Yeah image name can be updated at the same time as tags, I don't think there's any need to keep both image names.

**Comment by caspiano** [comment]
Cool, let's do it
