### ISSUE TITLE
Image scans

### ISSUE THREAD

**Issue by w-le** [PlaceOS/release#12]
Could we extend the github actions to include a vulnerability scan of the resulting docker images?

Can use something like this: https://github.com/Azure/container-scan

**Comment by kimburgess** [comment]
Definitely. We can do some of this at the repository level which will also include revalidation of existing images against new CVE's, but seems like a sensible step to also include minimum standards here _before_ an image is published.

Aside from base level linting and current known CVE checks, is there anything specifically that we're wanting protect against?

I'm not up to speed with the current best options for tooling, but am aware of the following:
1. the Azure action linked above (which wraps [Trivy](https://github.com/aquasecurity/trivy) and [Dockle](https://github.com/goodwithtech/dockle))
2. [snyk](https://snyk.io/product/container-vulnerability-management/) (which is used by DockerHub)
3. [clair](https://github.com/quay/clair) (quay.io's scanner)
4. [anchore](https://github.com/anchore/anchore-engine)

Any recommendation for/against these, or others that should be considered?

**Comment by w-le** [comment]
yep cool before the image is published is even better. I'm happy with just CVE checks, the linting is a bonus.
I haven't done much research into related tools yet sorry. My uninformed vote goes to option 1
