### ISSUE TITLE
Sync `placeos-models` across services

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/release#126]
Changes to email address handling introduced in [`placeos-models v5.9.0`](https://github.com/PlaceOS/models/blob/master/CHANGELOG.md#590) require all services that perform user lookup to progress past this version in unison in order to guarantee consistent behaviour.

This issue tracks changes associated with this.
- [x] auth: https://github.com/PlaceOS/auth/commit/b60ccdf50c7802c0c804bc58f2e73511ba59356f
- [x] build: https://github.com/PlaceOS/build/pull/30
- [x] core: https://github.com/PlaceOS/core/pull/129
- [x] dispatch: https://github.com/PlaceOS/dispatch/pull/7
- [x] edge: https://github.com/PlaceOS/core/pull/129
- [x] frontends: https://github.com/PlaceOS/frontends/pull/37
- [x] init: https://github.com/PlaceOS/init/pull/41
- [x] nginx: _NA_
- [x] rest-api: https://github.com/PlaceOS/rest-api/pull/180
- [x] rubber-soul: https://github.com/PlaceOS/rubber-soul/pull/37
- [x] source: https://github.com/PlaceOS/source/pull/16
- [x] staff-api: https://github.com/PlaceOS/staff-api/pull/102
- [x] triggers: https://github.com/PlaceOS/triggers/pull/12

**Comment by caspiano** [comment]
Related #1

**Comment by caspiano** [comment]
All PRs against this have been merged, thanks @kimburgess
