### ISSUE TITLE
Include `edge` service in release packaging

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/release#17]
Add service definition for building `edge` (https://github.com/PlaceOS/core/tree/feat/edge).

**Comment by kimburgess** [comment]
@caspiano I'm assuming that [Dockerfile.edge](https://github.com/PlaceOS/core/blob/feat/edge/Dockerfile.edge) is the appropriate point to build form?

**Comment by caspiano** [comment]
spot on

**Comment by kimburgess** [comment]
Holding off on this until https://github.com/PlaceOS/core/pull/47 merges.

https://github.com/PlaceOS/core/pull/63 in place to enable this to be added as a submodule, and pass service names to build task as `TARGET` arg.
