### ISSUE TITLE
WPA -> Desk Booking -> All Day Bookings only 1hr

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/release#240]
When creating an all day desk booking by checking the all day box, the booking is only created for 1 hr.

**Comment by MrYuion** [comment]
Hmm... Yeah that how it's been implemented, all day is just a flag on the booking.
The timezone becomes an issue for all day bookings when setting the duration.
I think all day is also a flag in Google and O365 data models for events.

**Comment by MrYuion** [comment]
Looking at my code it should be setting all day desk bookings to be 12+ hours in duration.
It also does seem to be working when testing it locally.

**Comment by jeremyw24** [comment]
@MrYuion this is still not working for desk bookings. This booking was created with all day ticked.
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/9bbd30f6-6e2d-411b-81f6-dc8b43010920)

**Comment by MrYuion** [comment]
Hmm... backend doesn't seem to be returning the `all_day` flag.
