### ISSUE TITLE
Apple/Google Wallet Integration

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/release#42]
Allow visitor passes and QR Codes for entry access systems to be added to Apple/Google Device wallets after the user has checked in using the Enrolment App.

**Comment by MrYuion** [comment]
There is browser level support for this in Safari and Chrome based browsers at least for payments.
https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API/Using_the_Payment_Request_API
