### ISSUE TITLE
.github repo for all orgs

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/release#54]
Configure .github repo for all Place Orgs and deploy automated labelling scheme.

**Comment by kimburgess** [comment]
Forks are now available via:
- https://github.com/place-labs/.github
- https://github.com/place-technology/.github

Actions are currently disabled on both of these. Before running an initial sync, @jeremyw24 can you please confirm that the following labels set are accurate / desired:

- [x] https://github.com/place-labs/.github/blob/main/labels.json
- [x] https://github.com/place-technology/.github/blob/main/labels.json

**Comment by jeremyw24** [comment]
Looks like the labels were 1 commit behind the current fixes, I have updated this in the other orgs so happy with this now.

**Comment by kimburgess** [comment]
Looks like the initial sync hits API rate limits pretty quickly with the default token (https://github.com/place-labs/.github/actions/runs/776090112).

Will need to slot a PAT in there for the initial run, then can revert to the default actions token for future updates.

**Comment by kimburgess** [comment]
Labels are all synced on `place-labs`. Currently in the process of running initial sync on `place-technology`.

Two issues have popped up during this process:
https://github.com/PlaceOS/.github/issues/14 (archived repos result in error)
https://github.com/PlaceOS/.github/issues/15 (rate limits being hit)
