### ISSUE TITLE
Issue on page Repositories

### ISSUE THREAD

**Issue by Bogdan-Vizcom** [PlaceOS/release#56]
**Describe the bug**
"Pull the latest commit for this repository" on Place OS Drivers repository fails and does not show a clear error or reason for the failure.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Repos
2. Click on Place OS Drivers
3. Click on Pull
4. After a little while see error: "Error pulling latest commit. Error: {}"

**Expected behaviour**
1. The repo is pulled successfully without error; or
2. If there is an error in pulling the repo, display information about the error which can help the user identify and rectify the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/74230005/98635947-cee6d900-2360-11eb-9a45-881f57c1cd86.png)
![image](https://user-images.githubusercontent.com/74230005/98635973-dc9c5e80-2360-11eb-8793-c19dc8083804.png)
![image](https://user-images.githubusercontent.com/74230005/98635986-e1f9a900-2360-11eb-95dc-b5b8eaf64ba4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 86.0.4240.183 (Official Build) (64-bit)

**Additional context**

**Hash:** b746e20
**Built:** 09 Nov 2020, 8:42 AM

**Comment by jeremyw24** [comment]
Detect 503 error and report please wait. Human readable status response.

**Comment by caspiano** [comment]
Issue moved to [PlaceOS/backoffice #201](https://github.com/PlaceOS/backoffice/issues/201) via [**ZenHub**](https://www.zenhub.com/)
