### ISSUE TITLE
Keep a CHANGELOG

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/release#62]
**Is your feature request related to a problem? Please describe.**

Users (including administrators) need a view of what has changed between versions. This can include new features, as well as bug fixes.

**Describe the solution you'd like**

[keep a CHANGELOG](https://keepachangelog.com/en/1.0.0/)

**Describe alternatives you've considered**

Automatically generate a list of changes from the semantic commit messages of all vendored services as a PR to the release branch, where it is reviewed, edited, then merged.

**Comment by jeremyw24** [comment]
Potential tool... https://changie.dev/guide/quick-start/

**Comment by caspiano** [comment]
We already conform to the conventional commit specification with allows us to autogenerate changelogs.
I’m sure there’s a github action we can use, or we can build one out.

The project level changelogs will be easy, nothing to really decide on.
However we must discuss how we want to present changes across the system for each platform release or whether we even want an autogenerated changelog for the platform releases at all.
I’m in favour of manually writing the changelog for the platform.

Another note should be keeping a migration guide for anything that cannot be resolved automatically, checkout [three.js migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide) for a great example
