### ISSUE TITLE
Application allows user to add Duplicate levels from the same file

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/release#70]
1. Application allows user to add Duplicate levels from the same file. There is no validation or error to notify the user of this
2. Application allows user to add Duplicate levels imported from different files. There is no validation or error to notify the user of this
3. 
![image](https://user-images.githubusercontent.com/83044454/115808217-6fbbe300-a42d-11eb-88ac-7d47db65d631.png)

**Comment by caspiano** [comment]
Hi @s-kadrolli,

If possible, could you relay what PlaceOS version you have (accessible via the admin tab), and which tags your services are pinned to in the partner-environment you are using?
This will help us reduce your issue and solve it as quick as possible.

**Comment by s-kadrolli** [comment]
Hi,

Below is screenshot, hope this is what you are looking for. Please let me know if you need any other information.



***@***.***D73851.79DDE290]

Best Regards,

Shiv Kadrolli
Senior Consultant
Australia | Project Services
NTT

M: +61 451 979 343
E: ***@***.******@***.***>
hello.global.ntt


P please consider the environment before printing this email

**Comment by caspiano** [comment]
@s-kadrolli sorry, I can't see an attached screenshot

**Comment by s-kadrolli** [comment]
Hi, I can see it in the email sent, do you have a direct email id I can send it to?

Best Regards,

Shiv Kadrolli
Senior Consultant
Australia | Project Services
NTT

M: +61 451 979 343
E: ***@***.******@***.***>
hello.global.ntt


P please consider the environment before printing this email

**Comment by kimburgess** [comment]
@s-kadrolli thanks for the issue! It looks looks like you are emailing these responses to the thread.

I have deleted your original messages as they contained personal information (phone number) from your footer, which you may not have intended to have posted publicly.

If you have access, you can respond directly in Github: https://github.com/PlaceOS/PlaceOS/issues/70. This will provide you the ability to attach those screenshots. Alternatively, please do feel free to get in touch with this information via support@place.technology.

**Comment by s-kadrolli** [comment]
Thanks Kim, i was responding from email notification that i got.

@caspiano , screenshot below:

![PlaceOS_Addminpng](https://user-images.githubusercontent.com/83044454/115831149-8c1f4600-a454-11eb-81cd-2ab0852a3a1b.png)

**Comment by caspiano** [comment]
Much appreciated @s-kadrolli!

**Comment by viv-4** [comment]
The issue is still present on a fresh deploy of `1.2105.1`
![image](https://user-images.githubusercontent.com/2793950/118741470-a69ce180-b891-11eb-9699-ac6caefcb062.png)
![image](https://user-images.githubusercontent.com/2793950/118741502-b6b4c100-b891-11eb-8332-7bd8ab8bc6ea.png)
