### ISSUE TITLE
Use crystal-client submodule

### ISSUE THREAD

**Issue by dukenguyenxyz** [PlaceOS/release#9]
`release` is supposed to imprint the state of all placeos libraries every time an update is produced. It would be more appropriate then for shards to reference `crystal-client` submodule inside `release` itself for specs and other purposes instead of the remote `crystal-client` on github (which is the current configuration at the moment in `shards.yml`).

**Comment by kimburgess** [comment]
Closing this off as the the work it references is currently within a WIP PR. The point is absolutely solid though - have added it into the [associated issue for that work](https://github.com/PlaceOS/PlaceOS/issues/7#issuecomment-805406204).
