### ISSUE TITLE
Meeting Room resources not flagged as resources

### ISSUE THREAD

**Issue by adamGuinea** [PlaceOS/release#96]
**Describe the bug**
POST request to /api/staff/v1/events is returning meeting room resources as attendees not flagged as `resource: true`

**Your environment**
Chrome browser
Staff API commit 1226db3
Calendar commit d78d485

**To Reproduce**
Create an event with POST request to /api/staff/v1/events 
Request payload: 
all_day: false
attendees: []
event_end: 1624291200
event_start: 1624285800
private: false
recurring: false
system_id: "system-id"
timezone: "Australia/Brisbane"
title: "Meeting"

I have attached a screenshot of the response

**Expected behavior**
Meeting rooms are flagged as a resource to make differentiating between them and people easier in the UI.

**Screenshots**
![Screenshot 2021-06-22 at 12 29 40](https://user-images.githubusercontent.com/43794777/122854501-261d4500-d357-11eb-96b5-9fc8c0765ad0.png)

**Additional context**
Currently using `visit_expected` to split up attendees and resources from the response payload.

**Comment by kimburgess** [comment]
Thanks for the report @adamGuinea!

An update is now available to the `staff-api` service which includes this. If your environment is using the rolling `edge` tag, the latest of this may be pulled. Alternatively, pinned environments may target `placeos/staff-api:42df8c5b762943df158a0cd2f42ee7271326ff14`.

For PlaceOS internal context, this has been resolved via https://github.com/place-labs/staff-api/issues/60.
